#!/bin/bash
DIRECTORY=$(dirname "$0")
echo "Changing to ${DIRECTORY}"
cd  "$DIRECTORY" || exit 1

echo "Run your project here."
python main.py "$@"
#python main.py dns01 --dir https://localhost:14000/dir --record 127.0.0.1 --domain netsec.ethz.ch --domain syssec.ethz.ch --revoke