#!/bin/bash

# stops processing in case of failure
set -euo pipefail

# prints each line executed
set -x

pwd

echo "Your solution goes here"

# Task 1 & 2
sudo cp nftables.conf /etc/nftables.conf
sudo systemctl restart nftables

# Task 3 - 5
sudo cp company-app.conf /etc/nginx/sites-enabled/company-app.conf

sudo apt-get install snapd -y
sudo snap install core
sudo snap install --classic certbot
sudo /snap/bin/certbot certonly -n --server http://acme.dtf.netsec.inf.ethz.ch/acme/default/directory -d remok.student.dtf.netsec.inf.ethz.ch --nginx --register-unsafely-without-email --agree-tos

sudo cp default-site.conf /etc/nginx/sites-enabled/default-site.conf
sudo cp nginx.conf /etc/nginx/nginx.conf
sudo systemctl restart nginx
